config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'users/new'

  get 'users/create'

  get 'toppages/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  
  get 'register', to: 'tasks#new'
  post 'register', to: 'tasks#create'
  
  
  put 'register/:id', to: 'tasks#done'
  
  resources :tasks, only: [:index, :edit, :update]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true, length: { maximum: 700}
  validates :content, presence: true, length: { maximum: 700}
  validates :tag, length: { maximum: 255}
  
  acts_as_taggable

end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email.downcase!}
  
  validates :name, length: {maximum: 50}
  validates :email, presence: true, length: {maximum: 255},
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: {case_sensitive: false}
  
  has_secure_password
  
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private 
  
  def whether_or_not_logged_in
    unless logged_in?
      redirect_to login_url
    end 
  end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:sessions][:email].downcase 
    password =params[:sessions][:password]
    
    if authentication(email, password)
      flash[:success] = "ログインに成功しました"
      redirect_to root_url 
    else 
      flash.now[:danger] = "ログインに失敗しました"
      render :new 
    end 
    
  end

  def destroy
    session[:user_id] = nil 
    flash[:success] = "ログアウトしました"
    redirect_to root_url
  end
  
  private
  
  def authentication(input_email, input_password)
    @user = User.find_by(email: input_email)
    
    if @user && @user.authenticate(input_password)
      session[:user_id] = @user.id 
      return true 
    else 
      return false
    end 
  end 
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :whether_or_not_logged_in

  def index
    #　@current_time, @messageの再取得
    #　標準時の時間のみ整数として取得し、日本時刻に調整
    @current_time = Time.now.strftime('%H').to_i + 9
    if (@current_time>=29 && @current_time<=33) || (@current_time>=9 && @current_time<=12)
      @message = 'おはようございます'
    elsif (@current_time >= 13 && @current_time <= 18)
      @message = 'こんにちは'
    elsif (@current_time >= 19 && @current_time <= 28)
      @message = 'こんばんは'
    end

    # @nameの再取得
    unless @current_user.name == nil
      @name = @current_user.name + "さん"
    else
      @name = "ユーザーさん"
    end

    # link_toからクリックされたタグを取得,絞り込みと再表示
    #:tasklist_tag_nameにタグ絞り込みがあった場合
    if params[:tasklist_tag_name]
      @done_tasks = @current_user.tasks.where('status >= 5')
      # @tasksもタグで絞り込みした上で再定義
      @tasks = Task.tagged_with("#{params[:tasklist_tag_name]}").where('status >= 0 && status <=4' )
      @active_tab=1
      render 'toppages/index'

      #:checklist_tag_nameにタグ絞り込みがあった場合
    elsif params[:checklist_tag_name]
      @tasks = @current_user.tasks.where('status >= 0 && status <=4' )
      @done_tasks = Task.tagged_with("#{params[:checklist_tag_name]}").where('status >= 5')
      @active_tab = 2
      render 'toppages/index'
    end

  end

  def new
    @task = Task.new
    render 'tasks/register'
  end

  def create
    @task = current_user.tasks.build(task_params)

    if @task.save
      # flash[:success] = "カードを作成しました!"
      redirect_to root_url
    else
      flash[:danger] = "カード作成に失敗しました"
      render :register
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])

    if @task.update(task_params)
      # flash[:success] = "カードを更新しました!"
      redirect_to root_url
    else
      flash[:danger] = "カード編集に失敗しました"
      render :register
    end

  end

  def destroy
  end



  def done
    # binding.pry
    params[:task].update(status: 5)
  end

  private

  def task_params
    params.require(:task).permit(:title, :content, :tag_list, :status)
  end

end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    
    
    if logged_in?
      unless @current_user.name == nil
      
      # 現在時刻の取得(9～33の範囲)
        #標準時の時間のみ整数として取得し、日本時刻に調整
        @current_time = Time.now.strftime('%H').to_i + 9
        if (@current_time>=29 && @current_time<=33) || (@current_time>=9 && @current_time<=12) 
          @message = 'おはようございます'
        elsif (@current_time >= 13 && @current_time <= 18)  
          @message = 'こんにちは'
        elsif (@current_time >= 19 && @current_time <= 28) 
          @message = 'こんばんは'
        end
        
      # ログインユーザ名の取得(ユーザ名登録時)
        @name = @current_user.name + "さん"
      else
      # ログインユーザ名の取得(ユーザ名が未登録)  
        @name = "ユーザーさん"
      end 
      
      @task = Task.new
      @tasks = @current_user.tasks.where('status >= 0 && status <=4' )
      @done_tasks = @current_user.tasks.where('status >= 5')
    end 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "登録完了しました！"
      redirect_to root_url
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end 
  end
  
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_cinfirmation)
  end 
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end 
  
  def logged_in?
    !!current_user
  end 
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <div class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%# <a class="navbar-brand" href="/">Reminder</a>-- %>
          <%= link_to 'Reminder', root_url, class: 'navbar-brand'%>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li><%= link_to @current_user.name, root_url %></li>
              <li><%= link_to 'Log out', logout_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'New Account', signup_path %></li>
              <li><%= link_to 'Log in', login_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Reminder</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    


    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages'%>
      
      <%= yield %>
    </div>
      
  </body>
</html>

app/views/tasks/_checklist.html.erb
<% done_tasks.each do |done_task| %>
    <section>
      <div class="accordion-title">
        <a href="#"><%= done_task.title %></a>
      </div>
      <div class="accordion-content"><%= done_task.content %></div>
      <% done_task.tag_list.each do |tag| %>
        <%= link_to tag, tasks_path(checklist_tag_name: tag), class:'tag'%>
      <% end %>
      <%= button_to 'もう一回' %>
      <%= button_to '1Day' %>
      <%= button_to '3Day' %>
      <%= button_to 'OK!' %>
    </section>
<% end %>

app/views/tasks/_graph.html.erb
<p>進捗状況</p>
<p>覚えた数：<%= @done_tasks.count %></p>

app/views/tasks/_tasklist.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">

      <%# タブ機能実装 %>
      <ul class="tabs-menu">
        <li><a href="#tabs-1">問題リスト: <%= tasks.count %></a></li>
        <li><a href="#tabs-2">チェックリスト: <%= done_tasks.count %></a></li>
        <li><a href="#tabs-3">進捗状況</a></li>
      </ul>


      <section class="tabs-content" data-tab-active="<%= @active_tab %>">
        <section id="tabs-1">

          <%# アコーディオン機能 %>
          <div class='accordion'>
            <% tasks.each do |task| %>
              <section>
                <%# タイトル(表)%>
                <div class="accordion-title">
                  <a href="#"><%= task.title %></a>
                </div>
                <%# 内容(裏)%>
                <div class="accordion-content">
                  <a href="#">
                    <%= task.content %>
                  </a>
                </div>
                <%#タグ表示 %>
                <% task.tag_list.each do |tag| %>
                  <%= link_to tag, tasks_path(tasklist_tag_name: tag), class:'tag'%>
                <% end %>
                <%# ボタン配置%>
                <% if task.status == 0 %>
                    <%= button_to 'もう一回', class: 'btn btn-primary' %>
                    <%= button_to '1Day' %>
                    <%= button_to '3Day' %>
                    <%# <%= button_to 'OK!', register_path(:task), method: :put, class: 'btn btn-success' %>
                  <% elsif task.status == 1 %>
                    <%= button_to 'もう一回' %>
                    <%= button_to '3Day' %>
                    <%= button_to '1Week' %>
                    <%= button_to 'OK!' %>
                  <% elsif task.status == 2 %>
                    <%= button_to '始めから' %>
                    <%= button_to 'もう一回' %>
                    <%= button_to '3Day' %>
                    <%= button_to '1Week' %>
                    <%= button_to '2Week' %>
                    <%= button_to 'OK!' %>
                  <% elsif task.status == 3 %>
                    <%= button_to '始めから' %>
                    <%= button_to 'もう一回' %>
                    <%= button_to '1Week' %>
                    <%= button_to '2Week' %>
                    <%= button_to '1Month' %>
                    <%= button_to 'OK!' %>
                  <% elsif task.status == 4 %>
                    <%= button_to '始めから' %>
                    <%= button_to 'もう一回' %>
                    <%= button_to '1Month' %>
                    <%= button_to '3Month' %>
                    <%= button_to 'OK!' %>
                <% end %>

                <%= button_to '編集', edit_task_path(task), {method: :get} %>
              </section>
            <% end %>
          </div>

        </section>


        <section id ="tabs-2">
          <% unless done_tasks == nil %>
            <%= render 'tasks/checklist', done_tasks: done_tasks, tasks: tasks %>
          <% else %>
            <p>復習する問題はありません</p>
          <% end %>
        </section>

        <section id ="tabs-3">
          <% unless done_tasks == nil %>
          <%= render 'tasks/graph', done_tasks: done_tasks %>
          <% end %>
        </section>
      </section>

  </div>
</div>

app/views/tasks/edit.html.erb
<div class="text-center">
  <h2>カードの編集</h2>
</div>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    
    <%= form_for(@task) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :title, '表面' %>
        <%= f.text_area :title, value: @task.title, size: '100*7', class: 'form-control', placeholder: '覚えたい内容を入力' %>
      </div>
      
      <div class="form-group">
        <%= f.label :content, '裏面' %>
        <%= f.text_area :content, value: @task.content, size: '100*7', class: 'form-control', placeholder: '覚えたい内容の答えを入力' %>
      </div>
    
      <div class="form-group">
        <%= f.label :tag_list, 'タグ' %>：<%= f.text_field :tag_list, value: @task.tag_list.join(','), class: 'form-control', "data-role" => "tagsinput" %>
      </div>
      
      <%= f.submit '変更', class: 'btn btn-primary pull-right'%>
    <% end %>
    
  </div>

</div>

app/views/tasks/register.html.erb
<div class="text-center">
  <h2>カードの作成</h2>
</div>


<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= form_for(@task, url: register_path) do |f| %>
    
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :title, '表面' %>
        <%= f.text_area :title, class: 'form-control', size: '100*7', placeholder: '覚えたい内容を入力'%>
      </div>
      
      <div class="form-group">
        <%= f.label :content, '裏面'%>
        <%= f.text_area :content, class: 'form-control', size: '100*7', placeholder: '覚えたい内容の答えを入力'%>
      </div>
      
      <div class="form-group">
        <%= f.label :tag_list, 'タグ' %>：<%= f.text_field :tag_list, class: 'form-control', "data-role" => "tagsinput"  %>
      </div>
      
      <%= f.hidden_field :status, :value => 0 %>
      <%= f.submit '登録', class: 'btn btn-primary pull-right' %>
      
    <% end %>
  </div> 
</div>

app/views/toppages/index.html.erb
<%#ログインしているか確認%>
<% if logged_in? %>
　<%# ログイン済%>
　<%# 冒頭のメッセージ%>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h3><%= @message %>、<%= @name %>。</h3>
      <h3>今日も一緒に頑張りましょう！</h3>
    </div>
　</div>
　<%# 暗記カード作成画面 %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <p class="card-making">～簡易暗記カード作成～</p>
      
      <%= form_for(:task, url: register_path) do |f| %>
        <%#= render 'layouts/error_messages', model: f.object %>
      
        <div class="form-group">
          <%= f.text_field :title, class: 'form-control', placeholder: '覚えたい内容を入力してください' %>
        </div>
        
        <div class="form-group">
          <%= f.text_field :content, class: 'form-control', placeholder: '覚えたい内容の答えを入力してください' %>
        </div>
        
        <%= f.hidden_field :status, :value => 0 %>
        <%= f.submit '登録',method: 'post', class: 'btn btn-primary pull-right btn-origin'%>
      <% end %>
      
      <%= button_to '詳細', {controller: 'tasks',action: 'new'}, method: :get, class: 'btn btn-success pull-right' %>      
      
    </div>
  </div>
  
  <%# Tasklistへrender。Taskを一覧表示する%>
  <%= render 'tasks/tasklist', {tasks:@tasks, done_tasks:@done_tasks }%>
  
<% else %>
　<%# ログイン未済%>
  <div class="mycontainer">
    <h1>Reminderへようこそ！！</h1>
    <h3>
      このアプリでは以下の事が出来ます<br>
      1.<br>
      2.<br>
      3.<br>
      是非、あなたの学習の手助けをさせてください！
    </h3>
    <h4>
      はじめてアプリを使われる方→<%= link_to 'New Account', signup_path %><br>
      既に会員登録されている方→<a href="#">Login</a><br>
    </h4>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="text-center">
  <h2>会員登録</h2>
</div>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
    
      <div class="form-group">
        <%= f.label :name, 'ユーザー名(任意)' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>  
    
      <div class="form-group">
        <%= f.label :email, 'メールアドレス(必須)' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :password, 'パスワード(必須)' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード確認(必須)' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      
      <%= f.submit 'Sign up!', class:' btn btn-primary btn-block register-btn'%>
      
    <% end %>
    
  </div>
</div>